---
title: "Laboratorio 2"
author: "Catalina Olivares y Xavier Muñoz Díaz"
date: "2024-06-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Librerías
```{r}
library(VIM)
library(impute)
library(ggplot2)
library(dplyr)
library(tidyr)
library(cluster)
library(factoextra)
library(stats)
library(arulesViz)
library(mice)
```

# Carga de datos
```{r setup, include=FALSE}
datos <- read.csv("kidney_disease.csv")
```

# Limpieza de datos
```{r}
# Reemplaza espacios en blanco con NA
copia_datos <- datos
copia_datos[copia_datos == ""] <- NA

# Imputación KNN
datos_imputados <- kNN(data = copia_datos, imp_var = FALSE)

# Quita columna id y de la clase
datos_limpios <- datos_imputados[,-1]
```

# Categorización de los datos
```{r}
# Convertir las columnas a numérico
variables_numericas <- c("age", "bp", "bgr", "bu", "sc", "sod", "pot", "hemo", "pcv", "wc", "rc", "al", "su")
datos_categoricos <- datos_limpios %>%
  mutate(across(all_of(variables_numericas), ~ as.numeric(as.character(.))))

# Cambia valor númerico de la edad por la categoría a la que pertenece
datos_categoricos <- datos_categoricos %>%
  mutate(age = case_when(
    age >= 2 & age < 6 ~ "primerainfancia",
    age >= 6 & age < 12 ~ "infancia",
    age >= 12 & age <= 18 ~ "adolescencia",
    age >= 19 & age <= 59 ~ "adultez",
    age >= 60 ~ "vejez",
  ))

# Cambia valor númerico de la presión arterial por la categoría a la que pertenece
datos_categoricos <- datos_categoricos %>%
  mutate(bp = case_when(
    bp < 120 ~ "hipotension",
    bp >= 120 & bp <= 129 ~ "normal",
    bp >= 130 & bp <= 140 ~ "hipertension",
    bp > 140 ~ "hipertension",
  ))

# Cambia valor númerico de la glucosa en sangre aleatoria por la categoría a la que pertenece
datos_categoricos <- datos_categoricos %>%
  mutate(bgr = case_when(
    bgr < 70 ~ "hipoglucemia",
    bgr >= 70 & bgr <= 99 ~ "normal",
    bgr >= 126 ~ "diabetes",
    bgr >= 100 & bgr <= 125 ~ "prediabetes",
  ))

# Cambia valor númerico bun por la categoría a la que pertenece,considerando normales los rangos de Infante: 3-16,niñez:4-18 Adolescencia: 7-20, Adultez y vejez: 8-25
datos_categoricos <- datos_categoricos %>%
  mutate(bu = case_when(
    age == "primerainfancia" & bu < 3 ~ "bajo",
    age == "primerainfancia" & bu >= 3 & bu < 16 ~ "normal",
    age == "primerainfancia" & bu >= 16 ~ "alto",
    age == "infancia" & bu < 4 ~ "bajo",
    age == "infancia" & bu >= 4 & bu < 18 ~ "normal",
    age == "infancia" & bu >= 18 ~ "alto",
    age == "adolescencia" & bu < 7 ~ "bajo",
    age == "adolescencia" & bu >= 7 & bu < 20 ~ "normal",
    age == "adolescencia" & bu >= 20 ~ "alto",
    age == "adultez" & bu < 8 ~ "bajo",
    age == "adultez" & bu >= 8 & bu < 25 ~ "normal",
    age == "adultez" & bu >= 25 ~ "alto",
    age == "vejez" & bu < 8 ~ "bajo",
    age == "vejez" & bu >= 8 & bu < 25 ~ "normal",
    age == "vejez" & bu >= 25 ~ "alto",
  ))

#Cambiar valores de sc por categorias conciderando normales los rangos de Infante: 0.24-0.41 , niñez:0.32-0.73,Adolescencia: 0.53-0.87,Adultez y vejez:0.5-1.20
datos_categoricos <- datos_categoricos %>%
  mutate(sc = case_when(
    age == "primerainfancia" & sc < 0.24 ~ "bajo",
    age == "primerainfancia" & sc >= 0.24 & sc <= 0.41 ~ "normal",
    age == "primerainfancia" & sc > 0.41 ~ "alto",
    age == "infancia" & sc < 0.32 ~ "bajo",
    age == "infancia" & sc >= 0.32 & sc <= 0.73 ~ "normal",
    age == "infancia" & sc > 0.73 ~ "alto",
    age == "adolescencia" & sc < 0.53 ~ "bajo",
    age == "adolescencia" & sc >= 0.53 & sc <= 0.87 ~ "normal",
    age == "adolescencia" & sc > 0.87 ~ "alto",
    age == "adultez" & sc < 0.5 ~ "bajo",
    age == "adultez" & sc >= 0.5 & sc <= 1.20 ~ "normal",
    age == "adultez" & sc > 1.20 ~ "alto",
    age == "vejez" & sc < 0.5 ~ "bajo",
    age == "vejez" & sc >= 0.5 & sc <= 1.20 ~ "normal",
    age == "vejez" & sc > 1.20 ~ "alto",
  ))



# Cambia valor númerico de sodio en sangre por la categoría a la que pertenece
datos_categoricos <- datos_categoricos %>%
  mutate(sod = case_when(
    sod < 135 ~ "hiponatremia",
    sod >= 135 & sod <= 145 ~ "normal",
    sod > 145 ~ "hipernatremia",
  ))

# Cambia valor númerico de potasio en sangre por la categoría a la que pertenece
datos_categoricos <- datos_categoricos %>%
  mutate(pot = case_when(
    pot < 3.5 ~ "hipokalemia",
    pot >= 3.5 & pot <= 5.0 ~ "normal",
    pot > 5.0 ~ "hiperkalemia",
  ))

#Cambiar valores de hemoglobina por categorias conciderando normales los rangos de primera infancia :11.5 – 13.5
#niños:11.5 – 15.5, adolescentes: 12.0 – 16.0, adultos: 12.0-17.5, vejez: 12.0-17.5, bajo eso es anemia y sobre eso poliglobulia
datos_categoricos <- datos_categoricos %>%
  mutate(hemo = case_when(
    age == "primerainfancia" & hemo < 11.5 ~ "anemia",
    age == "primerainfancia" & hemo >= 11.5 & hemo <= 13.5 ~ "normal",
    age == "primerainfancia" & hemo > 13.5 ~ "poliglobulia",
    age == "infancia" & hemo < 11.5 ~ "anemia",
    age == "infancia" & hemo >= 11.5 & hemo <= 15.5 ~ "normal",
    age == "infancia" & hemo > 15.5 ~ "poliglobulia",
    age == "adolescencia" & hemo < 12.0 ~ "anemia",
    age == "adolescencia" & hemo >= 12.0 & hemo <= 16.0 ~ "normal",
    age == "adolescencia" & hemo > 16.0 ~ "poliglobulia",
    age == "adultez" & hemo < 12.0 ~ "anemia",
    age == "adultez" & hemo >= 12.0 & hemo <= 17.5 ~ "normal",
    age == "adultez" & hemo > 17.5 ~ "poliglobulia",
    age == "vejez" & hemo < 12.0 ~ "anemia",
    age == "vejez" & hemo >= 12.0 & hemo <= 17.5 ~ "normal",
    age == "vejez" & hemo > 17.5 ~ "poliglobulia",
  ))
#Cambiar valores de pvc por categorias conciderando normales los rangos de primera infancia :75 – 87 niños:77 – 95, adolescentes: 78 – 102, adultos: 80 – 100, vejez: 80 – 100, bajo eso es microcitosis y sobre eso macrocitosis
datos_categoricos <- datos_categoricos %>%
  mutate(pcv = case_when(
    age == "primerainfancia" & pcv < 75 ~ "microcitosis",
    age == "primerainfancia" & pcv >= 75 & pcv <= 87 ~ "normal",
    age == "primerainfancia" & pcv > 87 ~ "macrocitosis",
    age == "infancia" & pcv < 77 ~ "microcitosis",
    age == "infancia" & pcv >= 77 & pcv <= 95 ~ "normal",
    age == "infancia" & pcv > 95 ~ "macrocitosis",
    age == "adolescencia" & pcv < 78 ~ "microcitosis",
    age == "adolescencia" & pcv >= 78 & pcv <= 102 ~ "normal",
    age == "adolescencia" & pcv > 102 ~ "macrocitosis",
    age == "adultez" & pcv < 80 ~ "microcitosis",
    age == "adultez" & pcv >= 80 & pcv <= 100 ~ "normal",
    age == "adultez" & pcv > 100 ~ "macrocitosis",
    age == "vejez" & pcv < 80 ~ "microcitosis",
    age == "vejez" & pcv >= 80 & pcv <= 100 ~ "normal",
    age == "vejez" & pcv > 100 ~ "macrocitosis",
  ))


# Cambia valor númerico de células blancas conciderando normales los rangos de primera infancia :5-17.0 niños:4.5 – 13.5 adolescentes: 4.5 – 13.0, adultos: 4.5 – 11.0, vejez: 4.5 – 11.0, bajo eso es leocopenia y sobre eso leucocitosis
datos_categoricos <- datos_categoricos %>%
  mutate(wc = case_when(
    age == "primerainfancia" & wc < 5 ~ "leucopenia",
    age == "primerainfancia" & wc >= 5 & wc <= 17.0 ~ "normal",
    age == "primerainfancia" & wc > 17.0 ~ "leucocitosis",
    age == "infancia" & wc < 4.5 ~ "leucopenia",
    age == "infancia" & wc >= 4.5 & wc <= 13.5 ~ "normal",
    age == "infancia" & wc > 13.5 ~ "leucocitosis",
    age == "adolescencia" & wc < 4.5 ~ "leucopenia",
    age == "adolescencia" & wc >= 4.5 & wc <= 13.0 ~ "normal",
    age == "adolescencia" & wc > 13.0 ~ "leucocitosis",
    age == "adultez" & wc < 4.5 ~ "leucopenia",
    age == "adultez" & wc >= 4.5 & wc <= 11.0 ~ "normal",
    age == "adultez" & wc > 11.0 ~ "leucocitosis",
    age == "vejez" & wc < 4.5 ~ "leucopenia",
    age == "vejez" & wc >= 4.5 & wc <= 11.0 ~ "normal",
    age == "vejez" & wc > 11.0 ~ "leucocitosis",
  ))


# Cambia valor númerico de células rojas en sangre por la categoría considerando normales los rangos de primera infancia :3.9 – 5.3 niños:4.0 – 5.2, adolescentes: 4.1 – 5.3, adultos: 4.0 – 5.99, vejez: 4.0 – 5.9 y bajo eso anemia y sobre eso poliglobulia
datos_categoricos <- datos_categoricos %>%
  mutate(rc = case_when(
    age == "primerainfancia" & rc < 3.9 ~ "anemia",
    age == "primerainfancia" & rc >= 3.9 & rc <= 5.3 ~ "normal",
    age == "primerainfancia" & rc > 5.3 ~ "poliglobulia",
    age == "infancia" & rc < 4.0 ~ "anemia",
    age == "infancia" & rc >= 4.0 & rc <= 5.2 ~ "normal",
    age == "infancia" & rc > 5.2 ~ "poliglobulia",
    age == "adolescencia" & rc < 4.1 ~ "anemia",
    age == "adolescencia" & rc >= 4.1 & rc <= 5.3 ~ "normal",
    age == "adolescencia" & rc > 5.3 ~ "poliglobulia",
    age == "adultez" & rc < 4.0 ~ "anemia",
    age == "adultez" & rc >= 4.0 & rc <= 5.99 ~ "normal",
    age == "adultez" & rc > 5.99 ~ "poliglobulia",
    age == "vejez" & rc < 4.0 ~ "anemia",
    age == "vejez" & rc >= 4.0 & rc <= 5.9 ~ "normal",
    age == "vejez" & rc > 5.9 ~ "poliglobulia",
  ))

# Cambia el valor numerico de al por categorias, considerando 0 muy bajo, 1 bajo ,2 medio,3 medio alto,4 alto y 5 muy alto
datos_categoricos <- datos_categoricos %>%
  mutate(al = case_when(
    al == 0 ~ "muybajo",
    al == 1 ~ "bajo",
    al == 2 ~ "medio",
    al == 3 ~ "medioalto",
    al == 4 ~ "alto",
    al == 5 ~ "muyalto",
  ))
# Cambia el valor numerico de su por categorias, considerando 0 muy bajo, 1 bajo ,2 medio,3 medio alto,4 alto y 5 muy alto
datos_categoricos <- datos_categoricos %>%
  mutate(su = case_when(
    su == 0 ~ "muybajo",
    su == 1 ~ "bajo",
    su == 2 ~ "medio",
    su == 3 ~ "medioalto",
    su == 4 ~ "alto",
    su == 5 ~ "muyalto",
  ))
```
## Obtención de reglas de asociación
```{r}
# Reglas de asociación
reglas = apriori(
    data = datos_categoricos, 
    parameter=list(support = 0.06, conf = 0.95, minlen = 3, maxlen = 26, target="rules"),
    appearance = list(rhs = c("classification=ckd", "classification=notckd"), default = "lhs"))

summary(reglas)

sorted_rules <- sort(reglas, by = "support", decreasing = TRUE)
inspect(head(sorted_rules, n = 20))

sorted_rules <- sort(reglas, by = "confidence", decreasing = TRUE)
inspect(head(sorted_rules, n = 20))

sorted_rules <- sort(reglas, by = "lift", decreasing = TRUE)
inspect(head(sorted_rules, n = 20))

```

```{r }
# Separa el data frame en dos, uno con los enfermos y otro con los sanos
enfermos <- datos_categoricos %>% filter(classification == "ckd")
sanos <- datos_categoricos %>% filter(classification == "notckd")


# Reglas de asociación para los enfermos
reglas_enfermos = apriori(
    data = enfermos, 
    parameter=list(support = 0.3, conf = 0.7, minlen = 2, maxlen = 26, target="rules"),
    appearance = list(rhs = c("classification=ckd"), default = "lhs"))

summary(reglas_enfermos)

sorted_rules <- sort(reglas_enfermos, by = "support", decreasing = TRUE)
inspect(head(sorted_rules, n = 10))

sorted_rules <- sort(reglas_enfermos, by = "confidence", decreasing = TRUE)
inspect(head(sorted_rules, n = 10))

sorted_rules <- sort(reglas_enfermos, by = "lift", decreasing = TRUE)
inspect(head(sorted_rules, n = 10))
```

```{r }
# Reglas de asociación para los sanos
reglas_sanos = apriori(
    data = sanos, 
    parameter=list(support = 0.3, conf = 0.7, minlen = 3, maxlen = 25, target="rules"),
    appearance = list(rhs = c("classification=notckd"), default = "lhs"))

summary(reglas_sanos)

sorted_rules <- sort(reglas_sanos, by = "support", decreasing = TRUE)
inspect(head(sorted_rules, n = 10))

sorted_rules <- sort(reglas_sanos, by = "confidence", decreasing = TRUE)
inspect(head(sorted_rules, n = 10))

sorted_rules <- sort(reglas_sanos, by = "lift", decreasing = TRUE)
inspect(head(sorted_rules, n = 10))
```