---
title: "lab1cata"
author: "Catalina Olivares"
date: "2024-04-08"
output: html_document
---

Instalación y apertura de librerías
```{r}
#install.packages("foreign")
#install.packages("RWeka") 
#install.packages("impute")

#library(VIM)
library(impute)


library(ggplot2)
library(dplyr)
library(tidyr)
```

Apertura de dataset
```{r setup, include=FALSE}

# Se selecciona el directorio del archivo
#setwd("/Users/chavy/Documents/Repositorios GitKraken/Laboratorios-AD/Lab-1")
#setwd("C:/Users/cata/Desktop/Analisislab1")

# Se carga el archivo CSV
datos <- read.csv("kidney_disease.csv")

# Comprueba que los datos se han cargado correctamente
#str(datos)
```

Limpieza de datos
```{r}
### borrar ###
num_filas <- nrow(datos)
print(paste("El dataframe 'datos' tiene", num_filas, "filas."))
##############

# Reemplazar espacio en blanco con NA
copia_datos <- datos
copia_datos[copia_datos == ""] <- NA

# Limpieza de variables 
#datos_limpios <- na.omit(datos)

# Imputación KNN
datos_imputados <- kNN(data = copia_datos, imp_var = FALSE)

# Quitar columna id
datos_limpios <- datos_imputados[,-1]

### borrar ###
num_filas_sin_NA <- nrow(datos_limpios)
print(paste("El dataframe 'datos_limpios' tiene", num_filas_sin_NA, "filas."))
##############
```

Normalización de datos
```{r}
datos_normalizados <- datos_limpios
# Binarización de variables categóricas
#######BORRAR -> los valores normal, present, yes, good y cdk toman el valor 1)
datos_normalizados$rbc <- ifelse(datos_normalizados$rbc == "normal", 1, 0)
datos_normalizados$pc <- ifelse(datos_normalizados$pc == "normal", 1, 0)
datos_normalizados$pcc <- ifelse(datos_normalizados$pcc == "present", 1, 0)
datos_normalizados$ba <- ifelse(datos_normalizados$ba == "present", 1, 0)
datos_normalizados$htn <- ifelse(datos_normalizados$htn == "yes", 1, 0)
datos_normalizados$dm <- ifelse(datos_normalizados$dm == "yes", 1, 0)
datos_normalizados$cad <- ifelse(datos_normalizados$cad == "yes", 1, 0)
datos_normalizados$appet <- ifelse(datos_normalizados$appet == "good", 1, 0)
datos_normalizados$pe <- ifelse(datos_normalizados$pe == "yes", 1, 0)
datos_normalizados$ane <- ifelse(datos_normalizados$ane == "yes", 1, 0)
datos_normalizados$classification <- ifelse(datos_normalizados$classification == "ckd", 1, 0)
```


Calculo media, mediana, moda y desviación estándar BORRAR<-----------
```{r}
#### BORRAR #####
#Calculo media y mediana
#medias <- sapply(datos_normalizados, mean, na.rm = TRUE)
#medianas <- sapply(datos_normalizados, median, na.rm = TRUE)

# Calculo moda de variables categóricas
#variables_categoricas <- c("rbc", "pc", "pcc", "ba", "htn", "dm", "cad", "appet", "pe", "ane", "classification")
#modas <- lapply(datos_normalizados[variables_categoricas], function(x) {
#  tab <- table(x)
#  names(tab)[tab == max(tab)]
#})

#desviaciones <- sapply(datos_normalizados, sd, na.rm = TRUE)

#Se crea un dataframe para la media, la mediana y la desviación estándar
#resultados <- data.frame(Media = medias, Mediana = medianas, Desvicion_Estandar = desviaciones)

#Se crea un dataframe para la moda
#resultados_moda <- data.frame(Moda = modas)

#print(resultados)
```

Conteo enfermos y sanos
```{r}
### BORRAR #### -> cdk/enferma? = 1, notcdk = 0 
# Contar personas enfermas (1) y sanas (0)
total_enfermos <- sum(datos_normalizados$classification == 1)
total_sanos <- sum(datos_normalizados$classification == 0)

# Contar personas sanas y enfermas en el conjunto de datos, datos
total_enfermos_datos <- sum(datos$classification == "ckd")
total_sanos_datos <- sum(datos$classification == "notckd")

# Mostrar los resultados 
print(paste("El número de personas enfermas es:", total_enfermos_datos))
print(paste("El número de personas sanas:", total_sanos_datos))

print(paste("El número de personas enfermas es:", total_enfermos))
print(paste("El número de personas sanas:", total_sanos))
```

Grafico de barras
```{r}
# Filtrar el número de personas enfermas y sanas
enfermos <- datos_normalizados %>% filter(classification == 1)
sanos <- datos_normalizados %>% filter(classification == 0)

# Crear un dataframe para la gráfica
estado_salud <- data.frame(estado = c("Enfermos", "Sanos"),
                           total_personas = c(total_enfermos, total_sanos))

# Calcula las proporciones 
proporciones_estado_salud <- round(estado_salud$total_personas / sum(estado_salud$total_personas), 2)
estado_salud$proporciones <- proporciones_estado_salud

# Gráfico de barras
ggplot(estado_salud, aes(x = estado, y = total_personas, fill = estado)) +
  geom_bar(stat = "identity") + 
  labs(x = "Estado de salud",
       y = "Cantidad de personas",
       title = "Comparación de personas enfermas y sanas") +
  scale_fill_manual(values = c("Enfermos" = "red", "Sanos" = "green")) +
  geom_text(aes(label = paste("Proporción:", proporciones)), vjust = -0.5) +
  theme_minimal()


```
calcular medidas de dispersion (rango ,varinza desviasion estandar, etc)
```{r}
# Seleccionar solo las columnas numéricas
# Filtrar el conjunto de datos original para obtener solo las personas enfermas
enfermas <- datos_normalizados[datos_normalizados$classification == 1, ]

enfermas_numericas <- enfermas[sapply(enfermas, is.numeric)]

# Calcular las medidas de dispersión para las variables numéricas
rangos_enfermas <- apply(enfermas_numericas, 2, function(x) diff(range(x, na.rm = TRUE)))
varianzas_enfermas <- apply(enfermas_numericas, 2, function(x) var(x, na.rm = TRUE))
desviaciones_enfermas <- apply(enfermas_numericas, 2, function(x) sd(x, na.rm = TRUE))
cuartiles_enfermas <- t(apply(enfermas_numericas, 2, function(x) quantile(x, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)))
coeficientes_variacion_enfermas <- apply(enfermas_numericas, 2, function(x) sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE) * 100)

# Crear un dataframe para las medidas de dispersión
resultados_dispersion_enfermas <- data.frame(
  Rango = rangos_enfermas, 
  Varianza = varianzas_enfermas, 
  Desviacion_Estandar = desviaciones_enfermas,
  Cuartil_25 = cuartiles_enfermas[, 1],
  Mediana = cuartiles_enfermas[, 2],
  Cuartil_75 = cuartiles_enfermas[, 3],
  Coeficiente_de_Variacion = coeficientes_variacion_enfermas
)
print (resultados_dispersion_enfermas)
```

```{r}
# Filtrar el conjunto de datos original para obtener solo las personas sanas
sanas <- datos_normalizados[datos_normalizados$classification == 0, ]

# Seleccionar solo las columnas numéricas para las personas sanas
sanas_numericas <- sanas[sapply(sanas, is.numeric)]

# Calcular las medidas de dispersión para las variables numéricas de las personas sanas
rangos_sanas <- apply(sanas_numericas, 2, function(x) diff(range(x, na.rm = TRUE)))
varianzas_sanas <- apply(sanas_numericas, 2, function(x) var(x, na.rm = TRUE))
desviaciones_sanas <- apply(sanas_numericas, 2, function(x) sd(x, na.rm = TRUE))
cuartiles_sanas <- t(apply(sanas_numericas, 2, function(x) quantile(x, probs = c(0.25, 0.5, 0.75), na.rm = TRUE)))
coeficientes_variacion_sanas <- apply(sanas_numericas, 2, function(x) sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE) * 100)

# Crear un dataframe para las medidas de dispersión de las personas sanas
resultados_dispersion_sanas <- data.frame(
  Rango = rangos_sanas, 
  Varianza = varianzas_sanas, 
  Desviacion_Estandar = desviaciones_sanas,
  Cuartil_25 = cuartiles_sanas[, 1],
  Mediana = cuartiles_sanas[, 2],
  Cuartil_75 = cuartiles_sanas[, 3],
  Coeficiente_de_Variacion = coeficientes_variacion_sanas
)
print(resultados_dispersion_sanas)
```

```{r}

# Filtrar el conjunto de datos original para obtener solo las personas enfermas
enfermas <- datos_normalizados[datos_normalizados$classification == 1, ]

# Seleccionar las variables categóricas
variables_categoricas <- c("rbc", "pc", "pcc", "ba", "htn", "dm", "cad", "appet", "pe", "ane")

# Crear un gráfico de barras para cada variable categórica
for (variable in variables_categoricas) {
  # Crear un dataframe para el gráfico de barras de esta variable
  datos_barras <- data.frame(valor = factor(enfermas[[variable]]))
  
  # Crear el gráfico de barras con colores personalizados
  p <- ggplot(datos_barras, aes(x = valor, fill = valor)) +
    geom_bar() +
    labs(title = paste("Distribución de", variable, "en personas enfermas"),
         x = variable,
         y = "Frecuencia") +
    theme_minimal() +
    scale_fill_manual(values = c("red", "green"))  # Color izquierdo (rojo), color derecho (verde)
  
  # Imprimir el gráfico
  print(p)
}

```

```{r}
# Filtrar el conjunto de datos original para obtener solo las personas sanas datos categ
sanas <- datos_normalizados[datos_normalizados$classification == 0, ]
# Imprimir tabla de frecuencia de cada variable categórica para personas sanas
for (variable in variables_categoricas) {
  print(table(sanas[[variable]]))
}

# Seleccionar las variables categóricas
variables_categoricas <- c("rbc", "pc", "pcc", "ba", "htn", "dm", "cad", "appet", "pe", "ane")

# Crear un gráfico de barras para cada variable categórica
for (variable in variables_categoricas) {
  # Crear un dataframe para el gráfico de barras de esta variable
  datos_barras <- data.frame(valor = factor(sanas[[variable]]))
  
  # Crear el gráfico de barras con colores personalizados
  p <- ggplot(datos_barras, aes(x = valor, fill = valor)) +
    geom_bar() +
    labs(title = paste("Distribución de", variable, "en personas sanas"),
         x = variable,
         y = "Frecuencia") +
    theme_minimal() +
    scale_fill_manual(values = c("red", "green"))  # Color izquierdo (rojo), color derecho (verde)
  
  # Imprimir el gráfico
  print(p)
}

```

```{r}
# Filtrar el conjunto de datos original para obtener solo las personas enfermas y sanas
#enfermas <- datos_normalizados[datos_normalizados$classification == 1, ]
#sanas <- datos_normalizados[datos_normalizados$classification == 0, ]

# Variables numericas
datos_numericos <- datos_normalizados %>%
  select_if(is.numeric)

# Crear boxplots para cada variable numérica

boxplots <- list()
for (columna in colnames(datos_numericos)) {
  boxplot_data <- bind_rows(
    mutate(enfermas, Estado = "Enfermo"),
    mutate(sanas, Estado = "Sano")
  ) %>%
    ggplot(aes(x = Estado, y = !!sym(columna), fill = Estado)) +
    geom_boxplot() +
    labs(title = paste("Boxplot de", columna),
         x = "Estado de Salud",
         y = "Valor") +
    theme_minimal()
  boxplots[[columna]] <- boxplot_data
}

# Mostrar boxplots
for (plot in boxplots) {
  print(plot)
}
#podemos obviar algunas variables ahi las escogemos las mas significativas

```